settings:
  title: "Status Page"
  url: "https://status.xvr.sh"
  logo: logo.png
  daysInHistogram: 90
  collectResponseTimes: true

  allmonitorsOperational: "Smooth sailing! ⛵"
  notAllmonitorsOperational: "Something is off 🧐️"
  monitorLabelOperational: "Operational"
  monitorLabelNotOperational: "Failing"
  monitorLabelNoData: "No data"
  dayInHistogramNoData: "No data"
  dayInHistogramOperational: "All good"
  dayInHistogramNotOperational: " incident(s)"

monitors:
  - id: xvr-sh
    name: swarmpit
    description: "docker swarm management platform"
    url: "https://xvr.sh"
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: dmc-web
    name: davidmoralescortes.com
    url: "https://davidmoralescortes.com"
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: dmc-blog
    name: losarchivosdecronos.com
    url: "https://losarchivosdecronos.com"
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: alexviscreanu-com
    name: alexviscreanu.com
    url: "https://alexviscreanu.com"
    method: GET
    expectStatus: 200
    followRedirect: true
